MvcKutuphane/Controllers/DuyuruController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcKutuphane.Models.Entity;

namespace MvcKutuphane.Controllers
{
    public class DuyuruController : Controller
    {
        // GET: Duyuru
        DBKUTUPHANEEntities3 db = new DBKUTUPHANEEntities3();
        public ActionResult Index()
        {
            var degerler = db.TBLDUYURU.ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult YeniDuyuru()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YeniDuyuru(TBLDUYURU t)
        {
            db.TBLDUYURU.Add(t);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DuyuruSil(int id)
        {
            var duyuru = db.TBLDUYURU.Find(id);
            db.TBLDUYURU.Remove(duyuru);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DuyuruDetay(TBLDUYURU p)
        {
            var duyuru = db.TBLDUYURU.Find(p.ID);
            return View("DuyuruDetay", duyuru);

        }
        public ActionResult DuyuruGuncelle(TBLDUYURU t)
        {
            var duyuru = db.TBLDUYURU.Find(t.ID);
            duyuru.KATEGORI = t.KATEGORI;
            duyuru.ICERIK = t.ICERIK;
            duyuru.TARIH = t.TARIH;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcKutuphane/Views/Duyuru/DuyuruDetay.cshtml
@model MvcKutuphane.Models.Entity.TBLDUYURU
@{
    ViewBag.Title = "DuyuruDetay";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>DuyuruDetay</h2>

@using (Html.BeginForm("DuyuruGuncelle", "Duyuru", FormMethod.Post))
{
    <div style="margin-bottom:15px"></div>
    <div class="form-group">
        @Html.LabelFor(k => k.ID)
        @Html.TextBoxFor(k => k.ID, new { @class = "form-control" })
        <br />
        <label>Duyuru Kategori</label>
        @Html.TextBoxFor(k => k.KATEGORI, new { @class = "form-control" })
        <br />
        <label>Duyuru İçerk</label>
        @Html.TextAreaFor(k => k.ICERIK, new { @class = "form-control" })
        <br />
        <label>Duyuru Tarih</label>
        @Html.TextBoxFor(k => k.TARIH, new { @class = "form-control" })
    </div>
    <div>
        <button class="btn btn-warning">Güncelle</button>
    </div>
}

MvcKutuphane/Views/Duyuru/Index.cshtml
@using MvcKutuphane.Models.Entity
@model List<TBLDUYURU>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
    string renk = "";
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>


<br />
<h2>Duyurular</h2>
<br />
<table class="table table-striped">
    <tr style="background-color:rgb(252,178,22)">
        <th>DUYURU NO</th>
        <th>KATEGORİ</th>
        <th>TARİH</th>
        <th>SİL</th>
        <th>İÇERİK</th>
    </tr>

    @foreach (var dyr in Model)
    {
        if (dyr.KATEGORI == "Diğer")
        {
            renk = "bg-info text-white";
        }
        if (dyr.KATEGORI == "Yeni Kitap")
        {
            renk = "bg-warning text-white";
        }
        if (dyr.KATEGORI == "İletişim")
        {
            renk = "bg-success text-white";
        }
        if (dyr.KATEGORI == "Kitapları Geciktirmeyin")
        {
            renk = "bg-danger text-white";
        }
        <tr class="@renk">
            <td>@dyr.ID</td>
            <td>@dyr.KATEGORI</td>
            <td>@Convert.ToDateTime(dyr.TARIH).ToString("dd/MM/yyyy")</td>
            <td><a href="/Duyuru/DuyuruSil/@dyr.ID" class="btn btn-danger">Sil</a></td>
            <td><a href="/Duyuru/DuyuruDetay/@dyr.ID" class="btn btn-default" style="background-color:cornflowerblue; color:white">Detaylar</a></td>
        </tr>
    }
</table>
<a href="/Duyuru/YeniDuyuru" class="btn btn-primary">Yeni Duyuru Ekle</a>

MvcKutuphane/Views/Duyuru/YeniDuyuru.cshtml
@model MvcKutuphane.Models.Entity.TBLDUYURU
@{
    ViewBag.Title = "YeniDuyuru";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>YeniDuyuru</h2>


<form class="form-group" method="post">
    <div style="margin-top:15px">
        <label>Duyuru Başlığı </label>
        @Html.TextBoxFor(x => x.KATEGORI, new { @class = "form-control" })

    </div>
    <div style="margin-top:15px">
        <label>Duyuru İçeriği</label>
        @Html.TextBoxFor(x => x.ICERIK, new { @class = "form-control" })

    </div>
    <div style="margin-top:15px">
        <label>Duyuru Traihi </label>
        @Html.TextBoxFor(x => x.TARIH, new { @class = "form-control" })

    </div>
    <div style="margin-top:15px">
        <button class=" btn btn-info" id="Btn1">Duyuru Ekle</button>
    </div>
</form>