MvcKutuphane/Controllers/AyarlarController.cs
using MvcKutuphane.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace MvcKutuphane.Controllers
{
    public class AyarlarController : Controller
    {
        // GET: Ayarlar
        DBKUTUPHANEEntities3 db = new DBKUTUPHANEEntities3();
      
        public ActionResult Index2()
        {
            var kullanicilar = db.TBLADMIN.ToList();
            return View(kullanicilar);
        }
        [HttpGet]
        public ActionResult YeniAdmin()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YeniAdmin(TBLADMIN t)
        {
            db.TBLADMIN.Add(t);
            db.SaveChanges();
            return RedirectToAction("Index2");
        }
        public ActionResult AdminSil(int id)
        {
            var admin = db.TBLADMIN.Find(id);
            db.TBLADMIN.Remove(admin);           
            db.SaveChanges();
            return RedirectToAction("Index2");
        }
        [HttpGet]
        public ActionResult AdminGuncelle(int id)
        {
            var admin = db.TBLADMIN.Find(id);
            return View("AdminGuncelle", admin);
        }
        [HttpPost]
        public ActionResult AdminGuncelle(TBLADMIN p)
        {
            var admin = db.TBLADMIN.Find(p.ID);
            admin.KULLANİCİ = p.KULLANİCİ;
            admin.SIFRE = p.SIFRE;
            admin.YETKI = p.YETKI;
            db.SaveChanges();
            return RedirectToAction("Index2");
        }
    }
}

MvcKutuphane/Views/Ayarlar/AdminGuncelle.cshtml
@model MvcKutuphane.Models.Entity.TBLADMIN
@{
    ViewBag.Title = "AdminGuncelle";
    Layout = "~/Views/Shared/Layout.cshtml";
}

@using (Html.BeginForm("AdminGuncelle", "Ayarlar", FormMethod.Post))
{
    <div style="margin-bottom:15px"></div>
    <div class="form-group">
        @Html.LabelFor(k => k.ID)
        @Html.TextBoxFor(k => k.ID, new { @class = "form-control" })
        <br />
        <label>Kullanıcı Adı</label>
        @Html.TextBoxFor(k => k.KULLANİCİ, new { @class = "form-control" })
        <br />
        <label>Şifre</label>
        @Html.TextBoxFor(k => k.SIFRE, new { @class = "form-control" })
        <br />
        <label>Yetki</label>
        @Html.TextBoxFor(k => k.YETKI, new { @class = "form-control" })
    </div>
    <div>
        <button class="btn btn-warning">Güncelle</button>
    </div>
}

MvcKutuphane/Views/Ayarlar/Index2.cshtml
@using MvcKutuphane.Models.Entity
@model List<TBLADMIN>
@{
    ViewBag.Title = "Index2";
    Layout = "~/Views/Shared/Layout.cshtml";
}
<script src="~/Scripts/jquery-3.3.1.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<link rel="stylesheet" href="/webprofil/plugins/fontawesome-free/css/all.min.css">
<br />
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Kullanıcı</th>
        <th>Yetki</th>
        <th>Sil</th>
        <th>Düzenle</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.ID</td>
            <td>@x.KULLANİCİ</td>
            <td>@x.YETKI</td>
            <td>
                <a class="btn btn-danger btn-sm" href="/Ayarlar/AdminSil/@x.ID">
                    <i class="fas fa-trash">
                    </i>
                    Sil
                </a>
            </td>
            <td>
                <a class="btn btn-info btn-sm" href="/Ayarlar/AdminGuncelle/@x.ID">
                    <i class="fas fa-pencil-alt">
                    </i>
                    Düzenle
                </a>
            </td>

        </tr>
    }
</table>
<br />
<button class="btn btn-primary" data-toggle="modal" data-target="#Modal1">Yeni Admin Ekle</button>

<div class="modal" id="Modal1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title">Admin Ekleme Paneli</h2>
            </div>
            <form method="post" action="/Ayarlar/YeniAdmin/">
                <div class="modal-body">
                    <label>Kullanıcı Adı</label>
                    <input type="text" name="KULLANİCİ" class="form-control" />  
                    <br />
                    <label>Şifre</label>
                    <input type="text" name="SIFRE" class="form-control" /> 
                    <br />
                    <label>Yetki</label>
                    <input type="text" name="YETKI" class="form-control" />
                    <br />
                    <button class="btn btn-info">Kaydet</button>
                </div>
            </form>
        </div>
    </div>
</div>

@*data-togle:geçiş yaptığı yer
    data-target:hedef*@